CAMERA_OFFSET_Y = 2
CAMERA_FOLLOW_OFFSET_Y = 3
CAMERA_OFFSET_DISTANCE = 5

SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800

BALL_SPEED = 8
BALL_ATTRITION = 0.992
BALL_GRAVITY = -0.65
BALL_BOUNCE = 0.5

HITBOX_BUFFER = 1

JETSKI_SPEED = 1.3
JETSKI_SPEED_BOOST = 2.5

BOOST_COST = 0.3
BOOST_AMOUNT = 35
MAX_BOOST = 100
BOOST_IN_MAP_LIMIT = 4
TIME_DELAY_SPAWN_BOOST = 3
BAR_BOOST_LEFT = 0.3
BAR_BOOST_TOP = -0.7
BAR_BOOST_BOTTOM = -0.8

FIELD_LENGTH = 120
FIELD_WIDTH = 80

FIELD_LENGTH_OFFSET = 20
FIELD_WIDTH_OFFSET = 20