CAMERA_OFFSET_Y = 2
CAMERA_FOLLOW_OFFSET_Y = 3
CAMERA_OFFSET_DISTANCE = 5

SCREEN_WIDTH = 1200
SCREE_HEIGHT = 800

BALL_SPEED = 8
BALL_ATTRITION = 0.995
BALL_GRAVITY = -0.5
BALL_BOUNCE = 0.7

HITBOX_BUFFER = 1

JETSKI_SPEED = 1
JETSKI_SPEED_BOOST = 2.5