CAMERA_OFFSET_Y = 2
CAMERA_FOLLOW_OFFSET_Y = 2
CAMERA_OFFSET_DISTANCE = 5

SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800

BALL_SPEED = 8
BALL_ATTRITION = 0.992
BALL_GRAVITY = -0.65
BALL_BOUNCE = 0.5

HITBOX_BUFFER = 1

JETSKI_SPEED = 1.3
JETSKI_SPEED_BOOST = 2.5
JETSKI_JUMP_STRENGTH = 2

BOOST_COST = 0.3
BOOST_AMOUNT = 35
MAX_BOOST = 100
BOOST_IN_MAP_LIMIT = 4
TIME_DELAY_SPAWN_BOOST = 3
BAR_BOOST_LEFT = 0.3
BAR_BOOST_TOP = -0.7
BAR_BOOST_BOTTOM = -0.8

FIELD_LENGTH = 120
FIELD_WIDTH = 80
FIELD_LENGTH_OFFSET = 20
FIELD_WIDTH_OFFSET = 20

OPPONENT_DIFFICULTY = 1.1
GROUND = 0.4
BALL_GROUND = 0.5
BOOST_GROUND = 0.7

PLAYER_START_POSITION = [6.5, GROUND, 5]
OPPONENT_START_POSITION = [-5.5, GROUND, -13]
BALL_START_POSITION = [0.5, BALL_GROUND, -4]

SPECTATORS_JUMP_AMPLITUDE = 0.7
BOOST_JUMP_AMPLITUDE = 1
AIR_SPEED_BOOST = 0.3

LOW_SPEC = False

FIELD_JUMP_AMPLITUDE = 0.15  
FIELD_JUMP_FREQUENCY = 1.0  
